name: Contributors

on:
  pull_request_target:
    types:
      - closed
      - reopened
      - converted_to_draft
      - review_requested
      - review_request_removed
      - synchronize

jobs:
  cleanup-labels:
    name: Cleanup Labels
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            let hadAllowedTests = false;

            try {
              labels = await github.rest.issues.listLabelsOnIssue({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              })

              if (labels.data.some(label => label.name === 'Status: ðŸ¤ž Run Tests')) {
                hadAllowedTests = true;
              }
            } catch (error) {
              console.error(error);
            }

            try {
              if (hadAllowedTests) {
                github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'Status: ðŸ¤ž Run Tests'
                });
              }
            } catch (error) {
              console.log(error);
            }
