name: "Pull Request / Unlabelled"

# -----------------------------------------------------------------------------
#
# Fired when a pull request is labeled.
#
# -----------------------------------------------------------------------------

on:
  pull_request:
    types:
      - unlabeled

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "Trigger"
    uses: auth0/auth0-PHP/.github/workflows/common.pr-details.save.yml@main
    with:
      number: ${{ github.event.number }}
      sha: ${{ github.sha }}
