name: Save Pull Request Details

on:
  workflow_call:
    inputs:
      number:
        required: true
        type: number
      sha:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  save:
    name: "Prepare"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - env:
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/number
          echo $PR_SHA > ./pr/sha

      - uses: actions/upload-artifact@v3
        with:
          name: pr_details
          path: pr/

      - run: exit 0
