name: "Pull Request / Labeled"

# -----------------------------------------------------------------------------
#
# Fired when a pull request is labeled.
#
# -----------------------------------------------------------------------------

on:
  pull_request:
    types:
      - labeled

permissions: {}

concurrency:
  group: "common.pull-request.labeled-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    name: "Trigger"
    uses: "${{ github.repository }}/.github/workflows/common.pr-details.save.yml@main"
    with:
      number: ${{ github.event.number }}
      sha: ${{ github.sha }}
