name: Composer

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  composer-normalize:
    if: ${{ github.event.label.name == 'ðŸ¤ž Run Tests' }}
    name: Normalize
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker://ergebnis/composer-normalize-action

  composer-validate:
    if: ${{ github.event.label.name == 'ðŸ¤ž Run Tests' }}
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: composer validate
