# This workflow will run after a merge to the main branch from a pull request.

on:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pest:
    name: "PEST"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: pcov

      - run: composer install --no-progress

      - run: vendor/bin/pest --order-by random --fail-on-risky --stop-on-defect --coverage --parallel

      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # pin@3.1.4
        with:
          directory: ./coverage/
          flags: unittests
