name: "Composer Validate"

on:
  pull_request_target: {}
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'run' || github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v3
      - run: composer validate
