name: "PEST"

on:
  pull_request:
  merge_group:
  push:
    branches: ["master", "main"]

permissions: {}

jobs:
  pest:
    name: "Scan"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: pcov

      - run: composer install --no-progress

      - run: vendor/bin/pest --order-by random --fail-on-risky --stop-on-defect --coverage --parallel

      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          flags: unittests
