name: "Composer Validate"

# This workflow will run after a pull request is opened or updated, assuming the pull request is labeled with "Vetted".

on:
  workflow_run:
    workflows:
      - "Pull Request / Run Checks"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    name: "Run Checks"
    runs-on: ubuntu-latest

    steps:
      # Not a pull request. Success.
      - if: ${{ github.event_name != 'pull_request' }}
        run: exit 0

      # Dependabot. Success.
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: exit 0

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: pcov
          extensions: mbstring
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: composer validate
