name: Static Analysis

on:
  pull_request_target:
    types: [labeled]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  configuration:
    name: Configure
    runs-on: ubuntu-latest
    outputs:
      allow-label: ${{ env.ALLOW_LABEL }}
    steps:
      - name: Save state
        run: |
          echo "ALLOW_LABEL=Status: ðŸ¤ž Run Tests" >> $GITHUB_ENV

  review-phpstan:
    name: PHPStan
    needs: configuration
    runs-on: ubuntu-latest

    # Determine if the label is present.
    if: github.event.label.name == needs.configuration.outputs.allow-label || github.ref_name == 'main'

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, openssl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-stable
      - run: vendor/bin/phpstan analyze --no-progress

  review-psalm:
    name: Psalm
    needs: configuration
    runs-on: ubuntu-latest

    # Determine if the label is present.
    if: github.event.label.name == needs.configuration.outputs.allow-label || github.ref_name == 'main'

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, openssl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-stable
      - run: vendor/bin/psalm --no-progress
